### ISSUE TITLE
No such file or directory: airports.gz when downloading via pip

### ISSUE THREAD

**Issue by purpledalek** [aashishvanand/airports-py#2]
hi, i appear to be havingan issue when importing this package, i get an error saying: `FileNotFoundError: [Errno 2] No such file or directory: venv\\lib\\site-packages\\airports\\airports.gz` is this a bug or something im doing wrong? the only code i need to write to get this error is `from airports import airport_data`

**Comment by purpledalek** [comment]
to add to this, i think the issue is that the data folder within the top level airports folder isn't being installed via pip install for some reason?

**Comment by purpledalek** [comment]
i managed to get the library woking by downloading and copying the airports.gz file from the zip folder when the code was downloaded

**Comment by aashishvanand** [comment]
Hi @purpledalek,
This issue has been completely fixed in version 2.0.0! 🎉
Root Cause: The airports.gz file wasn't being properly included in the PyPI package distribution, and the code was looking in the wrong location.
